GET http://localhost:3000/api/notes

###
GET http://localhost:3000/api/notes/68f7e0936a2488661bdfc5f4

###
DELETE http://localhost:3000/api/notes/68f7e0936a2488661bdfc5f4

###
POST http://localhost:3000/api/notes
Content-Type: application/json

{
    "title": "Nota #2",
    "description": "Descripcion de la primer nota creada para mi db"
}

###
PUT http://localhost:3000/api/notes/1010
Content-Type: application/json

{
    "title": "Ejemplo1"
}
