GET http://localhost:3000/api/notes

###
GET http://localhost:3000/api/notes/68f7e0936a2488661bdfc5f4

###
DELETE http://localhost:3000/api/notes/68f7e0936a2488661bdfc5f4

###
POST http://localhost:3000/api/notes
Content-Type: application/json

{
    "title": "Personal Growth Reading",
    "description": "Read at least 20 pages from a personal development or tech-related book. Write a quick summary of what stood out to you."
}

###
PUT http://localhost:3000/api/notes/68f7ddb258da891229c65c40
Content-Type: application/json

{
    "title": "Task 1",
    "description": "Finish the backend API"
}
